apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end-react
  name: front-end-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-react
  template:
    metadata:
      labels:
        app: front-end-react
    spec:
      containers:
        - name: front-end-react-container
          image: liv44/front-end-react:0.1.0
          ports:
            - containerPort: 3000