apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end-react
  name: front-end-react
spec:
  type: NodePort
  ports:
  - name: "front-end-react-service"
    port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: front-end-react
