apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  type: ClusterIP
  ports:
  - name: "user-service-service"
    port: 3001
    targetPort: 3001
  selector:
    app: user-service
